### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Skruf90** [blackat/popcorn-time-express-angular-mongodb-grunt#1]
Do you have commands to build this?

**Comment by blackat** [comment]
Hey man! you are right sorry but I have forgot to add some commands, I will do it asap. Thanks a lot for the attention.

**Comment by Skruf90** [comment]
Thx :)

**Comment by blackat** [comment]
Hi,
I have added a brief description to install packages and run the server. I have still some work to do to complete CRUD operations but the get and update work.
[Here](http://blackat.github.io/blog/2014/10/03/fullstack-javascript-web-application-part-2/) I am writing a more detailed tutorial about the project.
